from setuptools import setup

setup(
    name="dash_website",
    version="0.1",
    description="Website that shows the results on multi-dimensionality of aging.",
    packages=["dash_website"],
    requires=["setuptools", "wheel"],
    install_requires=[
        "boto3==1.18.19",
        "botocore==1.21.19",
        "Brotli==1.0.9",
        "click==8.0.1",
        "cycler==0.10.0",
        "dash==1.21.0",
        "dash-bootstrap-components==0.13.0",
        "dash-core-components==1.17.1",
        "dash-gif-component==1.1.0",
        "dash-html-components==1.1.4",
        "dash-table==4.12.0",
        "Flask==2.0.1",
        "Flask-Compress==1.10.1",
        "future==0.18.2",
        "gunicorn==20.1.0",
        "itsdangerous==2.0.1",
        "Jinja2==3.0.1",
        "jmespath==0.10.0",
        "joblib==1.0.1",
        "kiwisolver==1.3.1",
        "MarkupSafe==2.0.1",
        "matplotlib==3.4.2",
        "numpy==1.21.1",
        "pandas==1.3.1",
        "Pillow==9.3.0",
        "pip==21.1.3",
        "plotly==5.1.0",
        "pyarrow==5.0.0",
        "pyparsing==2.4.7",
        "python-dateutil==2.8.2",
        "pytz==2021.1",
        "s3transfer==0.5.0",
        "scikit-learn==0.24.2",
        "scipy==1.7.1",
        "six==1.16.0",
        "sklearn==0.0",
        "tenacity==8.0.1",
        "threadpoolctl==2.2.0",
        "urllib3==1.26.6",
        "Werkzeug==2.0.1",
    ],
    extras_require={
        "dev": ["tqdm", "openpyxl", "ipykernel", "nbformat", "black", "pyyaml"],
    },
    entry_points={"console_scripts": ["launch_local_website=dash_website.index:launch_local_website"]},
)
