ORDER_TYPES_HERITABILITY = {"custom": "Custom", "h2": "h²"}

DIMENSIONS_GWAS = [
    "All",
    "set_instances1.5x",
    "set_instances23",
    "Abdomen",
    "AbdomenLiver",
    "AbdomenPancreas",
    "Arterial",
    "ArterialCarotids",
    "ArterialPulseWaveAnalysis",
    "Biochemistry",
    "BiochemistryBlood",
    "BiochemistryUrine",
    "Brain",
    "BrainCognitive",
    "BrainMRI",
    "Eyes",
    "EyesFundus",
    "EyesOCT",
    "Hearing",
    "Heart",
    "HeartECG",
    "HeartMRI",
    "BloodCells",
    "Lungs",
    "Musculoskeletal",
    "MusculoskeletalFullBody",
    "MusculoskeletalHips",
    "MusculoskeletalKnees",
    "MusculoskeletalScalars",
    "MusculoskeletalSpine",
    "PhysicalActivity",
]


DIMENSIONS_GWAS_VOLCANO = [
    "*instances1.5x",
    "Abdomen",
    "AbdomenLiver",
    "ArterialPulseWaveAnalysis",
    "Biochemistry",
    "BiochemistryBlood",
    "BiochemistryUrine",
    "Brain",
    "BrainCognitive",
    "BrainMRI",
    "Eyes",
    "EyesFundus",
    "EyesOCT",
    "Hearing",
    "Heart",
    "HeartMRI",
    "ImmuneSystem",
    "Lungs",
    "Musculoskeletal",
    "MusculoskeletalFullBody",
    "MusculoskeletalHips",
    "MusculoskeletalKnees",
    "MusculoskeletalScalars",
    "MusculoskeletalSpine",
    "PhysicalActivity",
]


VOLCANO_TABLE_COLUMNS = {
    "dimension": "Dimension",
    "size_effect": "Size effect",
    "p_value": "p-value (if 0 then < 5 x 10^-6)",
    "chromosome": "Chromosome",
    "SNP": "SNP",
    "Gene": "Gene",
    "Gene_type": "Gene type",
}
